server:
  port: 8080
  base: /api
  host: http://localhost
import-data-csv:
  enable: true
  environment-type: DEV
  file-name: movielist.csv
spring:
  application:
    name: movies-data
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:movies;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: MOVIE
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    defaultSchema: public
    baseline-on-migrate: true
  servlet:
    Multipart:
      max-file-size: 2MB
      max-request-size: 2MB
logging:
  level:
      org:
          springframework: INFO
          hibernate: INFO
