CREATE SCHEMA MOVIE AUTHORIZATION sa;
SET SCHEMA MOVIE;

CREATE SEQUENCE IF NOT EXISTS WORST_MOVIES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PRODUCERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS STUDIOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS WORST_MOVIE_PRODUCERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS WORST_MOVIE_STUDIOS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS STUDIOS (
    `id` bigint AUTO_INCREMENT,
    `name` char(128) NOT NULL,
    CONSTRAINT PK_STUDIOS PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS WORST_MOVIES (
    `id` bigint AUTO_INCREMENT,
    `yea` char(128) NOT NULL,
    `title` char(128) NOT NULL,
    `winner` bit NOT NULL DEFAULT 0,
    CONSTRAINT PK_WORST_MOVIE PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS PRODUCERS (
    `id` bigint AUTO_INCREMENT,
    `name` char(128) NOT NULL,
    CONSTRAINT PK_PRODUCERS PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS WORST_MOVIE_PRODUCERS (
    `id` bigint AUTO_INCREMENT,
    `id_worst_movie` bigint NOT NULL,
    `id_producers` bigint NOT NULL,
    CONSTRAINT PK_WORST_MOVIE_PRODUCERS PRIMARY KEY (id_worst_movie,id_producers),
    CONSTRAINT FR_WORST_MOVIE_PRODUCERS FOREIGN KEY (id_worst_movie) REFERENCES WORST_MOVIES(id),
    CONSTRAINT FR_PRODUCER FOREIGN KEY (id_producers) REFERENCES PRODUCERS(id));

CREATE TABLE IF NOT EXISTS WORST_MOVIE_STUDIOS (
    `id` bigint AUTO_INCREMENT,
    `id_worst_movie` bigint NOT NULL,
    `id_studios` bigint NOT NULL,
    CONSTRAINT PK_WORST_MOVIE_STUDIOS PRIMARY KEY (id_worst_movie,id_studios),
    CONSTRAINT FR_WORST_MOVIE_STUDIOS FOREIGN KEY (id_worst_movie) REFERENCES WORST_MOVIES(id),
    CONSTRAINT FR_STUDIOS FOREIGN KEY (id_studios) REFERENCES STUDIOS(id));
